# bvi - Binary Visual Editor Makefile
#
# This is the Makefile for bvi - binary visual editor. If it has the name
# "Makefile.in" then it is a template for a Makefile;  to generate the actual
# Makefile, run "./configure", which is a configuration script generated by the
# "autoconf" program (constructs like "@foo@" will get replaced in the
# actual Makefile.
#
# Copyright (c) 1996-2003 by Gerhard Buergmann
# gerhard@puon.at
# 
# 1996-01-18 V 1.0.0
# 1999-01-15 V 1.1.0
# 1999-03-03 V 1.1.1
# 1999-10-22 V 1.2.0
# 2000-05-31 V 1.3.0 beta
# 2000-10-01 V 1.3.0 final
# 2003-07-03 V 1.3.2
#
###############################################

srcdir = .
prefix = /usr/local
exec_prefix = ${prefix}

bindir = $(DESTDIR)${exec_prefix}/bin
mandir = $(DESTDIR)${prefix}/share/man
libdir = $(DESTDIR)${exec_prefix}/lib

man1dir = $(mandir)/man1

OBJS   =  bvi.o comm.o set.o re.o io.o edit.o recomp.o bscript.o util.o ui.o
HEADER =  bvi.h set.h bscript.h util.h ui.h
BMOBJ  =  bmore.o bm_unix.o recomp.o
CC     =  gcc
CFLAGS =  -g -O2  -Wall -pedantic
DEFS   =  -DHAVE_CONFIG_H
LDFLAGS=  
LIBS   =   -lncurses -llua -lssl
SHELL  =  /bin/sh



INSTALL = /usr/bin/install -c
INSTALL_PROGRAM = ${INSTALL}
INSTALL_DATA = ${INSTALL} -m 644


all: bvi bmore

bvi: $(OBJS)
	$(CC) $(LDFLAGS) -o bvi $(OBJS) $(LIBS)

bmore: $(BMOBJ)
	$(CC) $(LDFLAGS) -o bmore $(BMOBJ) $(LIBS)

.c.o:
	$(CC) $(CFLAGS) $(DEFS) -c $<

bmore.o: bmore.c
	$(CC) $(CFLAGS) $(DEFS) -DHELPFILE=\"$(libdir)/bmore.help\" -c $<


install: all installdirs
	@echo "Installing bvi"
	@$(INSTALL_DATA) bvi.1 bmore.1 $(man1dir)
	@$(INSTALL_PROGRAM) -s bvi $(bindir)
	@$(INSTALL_PROGRAM) -s bmore $(bindir)
	@$(INSTALL_DATA) bmore.help $(libdir)
	@if [ -f $(bindir)/bview ]; then rm $(bindir)/bview; fi
	@if [ -f $(bindir)/bvedit ]; then rm $(bindir)/bvedit; fi
	@ln $(bindir)/bvi $(bindir)/bview
	@ln $(bindir)/bvi $(bindir)/bvedit

installdirs:
	$(SHELL) ${srcdir}/mkinstalldirs $(bindir) $(libdir) $(man1dir)

uninstall:
	@echo "Uninstalling bvi"
	@if [ -f $(bindir)/bview ]; then rm $(bindir)/bview; fi
	@if [ -f $(bindir)/bvedit ]; then rm $(bindir)/bvedit; fi
	@if [ -f $(bindir)/bvi ]; then rm $(bindir)/bvi; fi
	@if [ -f $(bindir)/bmore ]; then rm $(bindir)/bmore; fi
	@if [ -f $(libdir)/bmore.help ]; then rm $(libdir)/bmore.help; fi
	@if [ -f $(man1dir)/bvi.1 ]; then rm $(man1dir)/bvi.1; fi
	@if [ -f $(man1dir)/bmore.1 ]; then rm $(man1dir)/bmore.1; fi

clean:
	rm -f core *.o bvi bvi.exe bmore bmore.exe a.out

distclean: clean
	rm -f Makefile config.cache config.h config.log config.status
