bvi.exec("set color(hex,999,000,000)")
bvi.display_error("here is an example error message!")
bvi.msg_window("please, press any key to exit window")
bvi.scrolldown(5)
bvi.print(8, 15, 3, "here is lua scripting test")
